@API_HostAddress = http://localhost:5122

GET {{API_HostAddress}}/api/order/
Accept: application/json

###

POST {{API_HostAddress}}/api/order/
Accept: application/json
Content-Type: application/json
{
  "date": "2025-09-01",
  "total": 150.00,
  "shippingAddress" :
  {
    "street" : "123 Main St",
    "city" : "Anytown",
    "number" : 123
  }
}
###
